/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Store;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANSI UMESH BARI
 */
public class DashboardAd extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    /**
     * Creates new form DashboardAd
     */
    public DashboardAd() {
        initComponents();
        connect();
        showEmp();
        showProduct();
        showCategory();
        showSupplier();
    }
    
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/luffystore","root", "root");
             stmt = con.createStatement();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
    }  
    
    public void showEmp()
    {
        String sql = "Select * from employee";
        
        try
        {
            rs = stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("name"),rs.getString("email"),rs.getString("contact"), rs.getString("city")});               
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    
    public void showProduct()
    {
        String sql = "Select * from product";
        
        try
        {
            rs = stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel) product.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("name"),rs.getString("price"),rs.getString("quantity"), rs.getString("supplier")});               
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    
    public void showCategory()
    {
        String sql = "Select * from category";
        
        try
        {
            rs = stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("catname")});               
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    
    public void showSupplier()
    {
        String sql = "Select * from supplier";
        
        try
        {
            rs = stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("name"),rs.getString("contact"), rs.getString("city")});               
            }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        suppbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product = new javax.swing.JTable();
        Producttable = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        BillingTable = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        empbtn1 = new javax.swing.JButton();
        probtn = new javax.swing.JButton();
        billbtn = new javax.swing.JButton();
        categorybtn = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        suppbtn.setBackground(new java.awt.Color(255, 255, 102));
        suppbtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        suppbtn.setText("Supplier");
        suppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppbtnActionPerformed(evt);
            }
        });
        jPanel1.add(suppbtn);
        suppbtn.setBounds(30, 550, 270, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 170, 210, 41);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Quantity", "Price", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(product);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(450, 70, 380, 240);

        Producttable.setBackground(new java.awt.Color(0, 0, 0));
        Producttable.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Producttable.setForeground(new java.awt.Color(255, 255, 255));
        Producttable.setText("Product Information");
        jPanel2.add(Producttable);
        Producttable.setBounds(450, 40, 380, 30);

        Supplier.setBackground(new java.awt.Color(0, 0, 0));
        Supplier.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Supplier.setForeground(new java.awt.Color(255, 255, 255));
        Supplier.setText("Supplier Information");
        jPanel2.add(Supplier);
        Supplier.setBounds(450, 380, 380, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Contact", "City"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(450, 410, 380, 240);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Employee Information");
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 40, 380, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Contact", "City"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 70, 380, 240);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(20, 410, 380, 240);

        BillingTable.setBackground(new java.awt.Color(0, 0, 0));
        BillingTable.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        BillingTable.setForeground(new java.awt.Color(255, 255, 255));
        BillingTable.setText("Category Information");
        jPanel2.add(BillingTable);
        BillingTable.setBounds(20, 380, 380, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(320, 10, 850, 710);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admindash.jpg"))); // NOI18N
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 280, 150);

        empbtn1.setBackground(new java.awt.Color(255, 255, 102));
        empbtn1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        empbtn1.setText("Employee");
        empbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(empbtn1);
        empbtn1.setBounds(30, 240, 270, 50);

        probtn.setBackground(new java.awt.Color(255, 255, 102));
        probtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        probtn.setText("Product");
        probtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probtnActionPerformed(evt);
            }
        });
        jPanel1.add(probtn);
        probtn.setBounds(30, 330, 270, 50);

        billbtn.setBackground(new java.awt.Color(255, 255, 102));
        billbtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        billbtn.setText("Billing");
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });
        jPanel1.add(billbtn);
        billbtn.setBounds(30, 410, 270, 50);

        categorybtn.setBackground(new java.awt.Color(255, 255, 102));
        categorybtn.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        categorybtn.setText("Category");
        categorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorybtnActionPerformed(evt);
            }
        });
        jPanel1.add(categorybtn);
        categorybtn.setBounds(30, 480, 270, 50);

        logout.setBackground(new java.awt.Color(255, 255, 102));
        logout.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(30, 620, 270, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 1180, 740);

        setBounds(150, 20, 1226, 752);
    }// </editor-fold>//GEN-END:initComponents

    private void suppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppbtnActionPerformed
        // TODO add your handling code here: 
        Supplier s  = new Supplier();
        s.setVisible(true);
    }//GEN-LAST:event_suppbtnActionPerformed

    private void empbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empbtn1ActionPerformed
        // TODO add your handling code here:
        Emp_Page ep=new Emp_Page();
        ep.setVisible(true);
    }//GEN-LAST:event_empbtn1ActionPerformed

    private void probtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probtnActionPerformed
        // TODO add your handling code here:
        ProductPage pp = new ProductPage();
        pp.setVisible(true);
    }//GEN-LAST:event_probtnActionPerformed

    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
    }//GEN-LAST:event_billbtnActionPerformed

    private void categorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorybtnActionPerformed
        // TODO add your handling code here:
        Catagory c = new Catagory();
        c.setVisible(true);
    }//GEN-LAST:event_categorybtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Usertype u = new Usertype();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillingTable;
    private javax.swing.JButton Producttable;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton billbtn;
    private javax.swing.JButton categorybtn;
    private javax.swing.JButton empbtn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton logout;
    private javax.swing.JButton probtn;
    private javax.swing.JTable product;
    private javax.swing.JButton suppbtn;
    // End of variables declaration//GEN-END:variables
}
