/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Store;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MANSI UMESH BARI
 */
public class Emp_Page extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    ResultSet rs;
     int id=0;
    /**
     * Creates new form Emp_Page
     */
    public Emp_Page() {
        initComponents();
        connect();
        showData();
    }
    
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/luffystore","root", "root");
             stmt = con.createStatement();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
    }  
    public void showData()
    {
        String sql="Select *from employee";
        try {
            rs=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("email"),rs.getString("password"),rs.getString("contact"),rs.getString("salary"), rs.getString("city")});               
            }
            
        }  catch (Exception e) 
                 {
                 JOptionPane.showConfirmDialog(this, e);
                 }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchOption = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 0, 260, 70);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search Data From Employee");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(21, 6, 261, 35);
        jPanel2.add(searchField);
        searchField.setBounds(21, 47, 437, 36);

        searchOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Name", "Email", "Contact" }));
        searchOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOptionActionPerformed(evt);
            }
        });
        jPanel2.add(searchOption);
        searchOption.setBounds(630, 10, 320, 40);

        search.setBackground(new java.awt.Color(255, 0, 0));
        search.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(630, 60, 320, 33);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 280, 1040, 100);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("City");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(720, 180, 50, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 70, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 190, 90, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 90, 90, 26);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(700, 90, 110, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("Salary");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 180, 70, 26);
        jPanel1.add(email);
        email.setBounds(460, 90, 230, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(130, 90, 230, 30);
        jPanel1.add(password);
        password.setBounds(810, 90, 210, 30);
        jPanel1.add(contact);
        contact.setBounds(140, 180, 220, 30);
        jPanel1.add(salary);
        salary.setBounds(460, 180, 230, 30);
        jPanel1.add(city);
        city.setBounds(800, 180, 220, 30);

        submit.setBackground(new java.awt.Color(255, 0, 0));
        submit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(1060, 90, 90, 30);

        update.setBackground(new java.awt.Color(255, 0, 0));
        update.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(1060, 160, 90, 30);

        delete.setBackground(new java.awt.Color(255, 0, 0));
        delete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(1060, 220, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(9, 6, 1160, 390);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Password", "Contact", "Salary", "City"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 420, 1060, 200);

        setBounds(180, 30, 1188, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        id = Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        name.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
        email.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
        password.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
        contact.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
        salary.setText(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
        city.setText(model.getValueAt(jTable1.getSelectedRow(), 6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(searchOption.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(this, "Please select Option in option list ");
        }
        else if(searchField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter data from textfiled ");
        }
        else{
            String sql = "select * from employee where "+searchOption.getSelectedItem()+" like '%"+searchField.getText()+"%' ";
            try {
                rs = stmt.executeQuery(sql);
                DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("email"),rs.getString("password"),rs.getString("contact"),rs.getString("salary"), rs.getString("city")});               
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String sql="insert into employee(name,email,password,contact,salary,city) values('"+name.getText()+"','"+email.getText()+"','"+password.getText()+"','"+contact.getText()+"','"+salary.getText()+"','"+city.getText()+"')";
        
        try{
            int i=stmt.executeUpdate(sql);
            if(i==1)
            {
                JOptionPane.showMessageDialog(this, "record inserted successfully");
                showData();
                
            }else {
                     JOptionPane.showMessageDialog(this, "Something went wrong");
                
            }
        }  catch (Exception e){
                         JOptionPane.showMessageDialog(this, e);
                    }
    }//GEN-LAST:event_submitActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         String sql = "update employee set name = '"+name.getText()+"', email ='"+email.getText()+"',password = '"+password.getText()+"',contact = '"+contact.getText()+"',salary ='"+salary.getText()+"',city ='"+city.getText()+"' where id = '"+id+"'";
         try {
                int i = stmt.executeUpdate(sql);
                if(i==1)
                {
                     JOptionPane.showMessageDialog(this, i+" record update succesfully!");
                     showData();
                }
                else{
                     JOptionPane.showMessageDialog(this, "Something went wrong");
                    }
             } catch (Exception e)
                    {
                     JOptionPane.showMessageDialog(this, e);
                    }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        String sql = "delete from employee where id = '"+id+"'";
        try {
            int i = stmt.executeUpdate(sql);
            if(i==1)
            {
                JOptionPane.showMessageDialog(this, i+" record delete succesfully!");
                showData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Something went wrong");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField salary;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> searchOption;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
