/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Store;

/**
 *
 * @author MANSI UMESH BARI
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Inventory Managing");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 40, 380, 50);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(110, 330, 450, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 19, 643, 360);

        setBounds(200, 50, 692, 421);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FirstPage fp=new FirstPage();
       fp.setVisible(true);
       Usertype uf =new Usertype();
       
       try{
           for(int i=1;i<100;i++){
           Thread.sleep(60);
           fp.jProgressBar1.setValue(i);
                      
           }
           fp.setVisible(false);
           
           uf.setVisible(true);
           
            
       }catch(Exception e){
       
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
