/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Store;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MANSI UMESH BARI
 */
public class ProductPage extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    ResultSet rs;
     int id=0;
    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println(e);
        }
        connect();
        addCategory();
        addSupplier();
        showData();
    }
    public void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/luffystore", "root", "root");
            stmt = con.createStatement();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public void showData()
    {
        try {
            String sql="select *from product";
            rs=stmt.executeQuery(sql);
            
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getString("price"),rs.getString("quantity"),rs.getString("category"),rs.getString("supplier")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public void addCategory()
    {
        try {
            String sql = "Select * from category";
            
            rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                cat.addItem(rs.getString("catname"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
   public void addSupplier()
    {
        try {
            String sql = "Select * from supplier";
            
            rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                supp.addItem(rs.getString("name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchOption = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cat = new javax.swing.JComboBox<>();
        supp = new javax.swing.JComboBox<>();
        Clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setText("Product");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 10, 210, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(820, 100, 90, 30);
        jPanel1.add(name);
        name.setBounds(120, 100, 260, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 100, 60, 30);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search Data From Product");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(21, 6, 261, 35);
        jPanel2.add(searchField);
        searchField.setBounds(21, 47, 437, 36);

        searchOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Name", "Email", "Contact" }));
        searchOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOptionActionPerformed(evt);
            }
        });
        jPanel2.add(searchOption);
        searchOption.setBounds(630, 10, 320, 40);

        search.setBackground(new java.awt.Color(255, 0, 0));
        search.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(630, 60, 320, 33);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 320, 1130, 100);
        jPanel1.add(price);
        price.setBounds(520, 100, 250, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 60, 30);
        jPanel1.add(quantity);
        quantity.setBounds(920, 100, 220, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("Category");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 180, 80, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("Supplier");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 180, 80, 30);

        submit.setBackground(new java.awt.Color(255, 0, 0));
        submit.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(810, 180, 90, 30);

        update.setBackground(new java.awt.Color(255, 0, 0));
        update.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(920, 180, 90, 30);

        delete.setBackground(new java.awt.Color(255, 0, 0));
        delete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(1040, 180, 90, 30);

        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });
        jPanel1.add(cat);
        cat.setBounds(120, 190, 260, 30);

        supp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppActionPerformed(evt);
            }
        });
        jPanel1.add(supp);
        supp.setBounds(530, 180, 240, 30);

        Clear.setBackground(new java.awt.Color(255, 0, 0));
        Clear.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(790, 250, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1150, 430);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Quantity", "Category", "Supplier"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 1140, 402);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 440, 1150, 350);

        setBounds(200, 50, 1179, 811);
    }// </editor-fold>//GEN-END:initComponents

    private void searchOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchOptionActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(searchOption.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(this, "Please select Option in option list ");
        }
        else if(searchField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter data from textfiled ");
        }
        else{
            String sql = "select * from product where "+searchOption.getSelectedItem()+" like '%"+searchField.getText()+"%' ";
            try {
                rs = stmt.executeQuery(sql);
                DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("price"),rs.getString("quantity"),rs.getString("category"),rs.getString("supplier")});
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        id=Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
       
        name.setText(model.getValueAt(jTable1.getSelectedRowCount(), 1).toString());
        price.setText(model.getValueAt(jTable1.getSelectedRowCount(), 2).toString());
        quantity.setText(model.getValueAt(jTable1.getSelectedRowCount(), 3).toString());
        cat.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
        supp.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    try {
            String sql="delete from product where id ="+id+"";
            int a=stmt.executeUpdate(sql);
            if(a==1)
            {
                JOptionPane.showMessageDialog(this, a+"Record delete sucessfully");
                showData();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Something went qrong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try {
            String sql="insert into product(name,price,quantity,category,supplier)" +"values('"+name.getText()+"','"+price.getText()+"',"+quantity.getText()+","+"'"+cat.getSelectedItem()+"','"+supp.getSelectedItem()+"')";
            int a=stmt.executeUpdate(sql);
            if(a==1)
            {
                JOptionPane.showMessageDialog(this, a+"Record insert succesfully");
                showData();
                        
            }
            else{
                JOptionPane.showMessageDialog(this, "Something went wrong!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            String sql="update product set name='"+name.getText()+"',price='"+price.getText()+"',"+"quantity="+quantity.getText()+",category='"+cat.getSelectedItem()+"',"+"supplier= '"+supp.getSelectedItem()+"' where id="+id+"";
            int a=stmt.executeUpdate(sql);
            if(a==1)
            {
            JOptionPane.showMessageDialog(this,a+"Record update sucessfully");
            showData();
                    
            }
            else{
                JOptionPane.showMessageDialog(this,"Something went wrong");
            }}
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_updateActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
         name.setText("");
        price.setText("");
        quantity.setText("");
        cat.setSelectedItem("");
        supp.setSelectedItem("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> searchOption;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> supp;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
